classdef SignalState < uint8
    enumeration
        SIGSTATE_UNDEFINED (0)
        SIGSTATE_INVALID (1)
        SIGSTATE_INITIALIZING (2)
        SIGSTATE_SIGNALSTATE_UPDATED (3)
        SIGSTATE_SIGNALSTATE_EXTRAPOLATED (4)
        SIGTATE_SIGNALSTATE_HOLD (5)
        SIGSTATE_SIGNALSTATE_CALIBRATING (6)
    end
end